bind = ["udp://0.0.0.0:9000", "tcp://127.0.0.1:8001"]

connect = ["udp://127.0.0.1:9002"]

#[multicast]
#addr = "244.10.10.10"
#port = 9000

[broker]
subscribe = ["/users/AstroRabbit/ISSOrbit"]

#[limits.connect]

# Server limits to control user agents
#[limits.bind]
#rate_bps = 4096

[net]
poll_buffer_size = 128
