[[socket]]
mode = "Bind"
addr = "udp://0.0.0.0:9000"

[[socket]]
mode = "Connect"
addr = "udp://127.0.0.1:9001"

#[[socket]]
#mode = "Connect"
#addr = "tcp://relay.olivr.dev:9069/"
#subscribe = []

#[multicast]
#addr = "244.10.10.10"
#port = 9000

[broker]

#[limits.connect]

# Server limits to control user agents
#[limits.bind]
#rate_bps = 4096

[net]
poll_buffer_size = 128
